version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: gamehub
    ports:
      - "3306:3306"
  favorites:
    build: ./services/favorites-service
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: rootpass
      DB_NAME: gamehub
      JWT_SECRET: super_secreto_cambia_esto
    ports:
      - "5000:5000"
    depends_on:
      - db
