openapi: 3.0.3
info:
  title: Favorites Service
  version: "1.0.0"
servers:
  - url: http://localhost:5000/api
paths:
  /favorites:
    get:
      summary: Listar favoritos del usuario autenticado
      security: [{ bearerAuth: [] }]
      responses:
        '200': { description: OK }
  /favorites/{idOrCode}:
    post:
      summary: Agregar a favoritos
      security: [{ bearerAuth: [] }]
      parameters:
        - in: path
          name: idOrCode
          schema: { type: string }
          required: true
      responses:
        '200': { description: OK }
    delete:
      summary: Eliminar de favoritos
      security: [{ bearerAuth: [] }]
      parameters:
        - in: path
          name: idOrCode
          schema: { type: string }
          required: true
      responses:
        '200': { description: OK }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
